name: manga_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.0
  dio: ^5.9.0
  email_validator: ^3.0.0
  filter_list: ^1.0.3
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_popup: ^3.3.9
  google_nav_bar: ^5.0.7
  image_picker: ^1.2.1
  internet_connection_checker_plus: ^2.9.1+2
  multi_select_flutter: ^4.1.3
  percent_indicator: ^4.2.5
  readmore: ^3.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/img/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Light.ttf
       



